// ═══════════════════════════════════════════════════════
//  Greek Mythology Primary Texts — books-data.js
//  All ISBNs verified · Translators confirmed · 2024
// ═══════════════════════════════════════════════════════

function coverUrl(isbn13) {
  return `https://books.google.com/books/content?vid=ISBN${isbn13}&printsec=frontcover&img=1&zoom=1`;
}

function amazonIn(isbn10) {
  return `https://www.amazon.in/dp/${isbn10}`;
}

function abebooks(isbn13) {
  return `https://www.abebooks.com/servlet/SearchResults?isbn=${isbn13}`;
}

// ─────────────────────────────────────────────────────
//  SHEET 1: EPIC ORIGINS
// ─────────────────────────────────────────────────────
const epicOrigins = [
  // ── HESIOD ────────────────────────────────────────
  {
    workTitle:    "Theogony & Works and Days",
    author:       "Hesiod",
    date:         "c. 700 BC",
    editions: [
      {
        type:        "English Translation",
        translator:  "M. L. West",
        publisher:   "Oxford University Press",
        series:      "Oxford World's Classics",
        year:        1999,
        pages:       112,
        isbn:        "9780192839411",
        isbn10:      "0192839411",
        notes:       "Acclaimed translation by the leading Hesiod scholar. Clear, precise, indispensable.",
        goodreads:   "https://www.goodreads.com/book/show/27418",
        premium:     null,
        premiumUrl:  null,
      },
      {
        type:        "Greek-English (Loeb)",
        translator:  "Glenn W. Most",
        publisher:   "Harvard University Press",
        series:      "Loeb Classical Library No. 57",
        year:        2007,
        pages:       308,
        isbn:        "9780674996229",
        isbn10:      "0674996224",
        notes:       "Revised Loeb edition with facing Greek text. The scholarly standard.",
        goodreads:   "https://www.goodreads.com/book/show/694475",
        premium:     null,
        premiumUrl:  null,
      },
    ],
  },

  // ── HOMER: ILIAD ──────────────────────────────────
  {
    workTitle:    "The Iliad",
    author:       "Homer",
    date:         "c. 8th century BC",
    editions: [
      {
        type:        "English Translation",
        translator:  "Richmond Lattimore",
        publisher:   "University of Chicago Press",
        series:      null,
        year:        2011,
        pages:       528,
        isbn:        "9780226470498",
        isbn10:      "0226470490",
        notes:       "The gold standard translation for 70 years. Faithful to Homer's dactylic rhythm.",
        goodreads:   "https://www.goodreads.com/book/show/11054461",
        premium:     "The Folio Society",
        premiumUrl:  "https://www.foliosociety.com/row/iliad.html",
      },
      {
        type:        "English — Alternative",
        translator:  "Robert Fagles",
        publisher:   "Penguin Classics",
        series:      "Penguin Classics",
        year:        1990,
        pages:       683,
        isbn:        "9780140275360",
        isbn10:      "0140275363",
        notes:       "Vivid, fast-moving verse. Introduction by Bernard Knox. Ideal for first-time readers.",
        goodreads:   "https://www.goodreads.com/book/show/1371",
        premium:     "The Folio Society",
        premiumUrl:  "https://www.foliosociety.com/row/iliad.html",
      },
      {
        type:        "Greek-English (Loeb) 2 vols",
        translator:  "A. T. Murray, rev. William F. Wyatt",
        publisher:   "Harvard University Press",
        series:      "Loeb Classical Library No. 170 & 171",
        year:        1999,
        vol1Pages:   608,
        vol2Pages:   668,
        isbn1:       "9780674995796",
        isbn2:       "9780674995802",
        isbn10:      "0674995791",
        notes:       "Greek text with facing English. Two volumes. The complete scholarly reference.",
        goodreads:   "https://www.goodreads.com/series/293440",
        premium:     null,
        premiumUrl:  null,
      },
    ],
  },

  // ── HOMER: ODYSSEY ────────────────────────────────
  {
    workTitle:    "The Odyssey",
    author:       "Homer",
    date:         "c. 8th century BC",
    editions: [
      {
        type:        "English Translation",
        translator:  "Emily Wilson",
        publisher:   "W. W. Norton & Company",
        series:      null,
        year:        2017,
        pages:       592,
        isbn:        "9780393089059",
        isbn10:      "0393089053",
        notes:       "First translation by a woman. Fresh, precise, and contemporary. The modern definitive version.",
        goodreads:   "https://www.goodreads.com/book/show/30940200",
        premium:     "The Folio Society",
        premiumUrl:  "https://www.foliosociety.com/row/odyssey.html",
      },
      {
        type:        "English — Alternative",
        translator:  "Robert Fagles",
        publisher:   "Penguin Classics",
        series:      "Penguin Classics",
        year:        1996,
        pages:       541,
        isbn:        "9780140268867",
        isbn10:      "0140268863",
        notes:       "Acclaimed verse translation with superb introduction by Bernard Knox.",
        goodreads:   "https://www.goodreads.com/book/show/333706",
        premium:     "The Folio Society",
        premiumUrl:  "https://www.foliosociety.com/row/odyssey.html",
      },
      {
        type:        "Greek-English (Loeb) 2 vols",
        translator:  "A. T. Murray, rev. George E. Dimock",
        publisher:   "Harvard University Press",
        series:      "Loeb Classical Library No. 104 & 105",
        year:        1995,
        vol1Pages:   496,
        vol2Pages:   467,
        isbn1:       "9780674995611",
        isbn2:       "9780674995628",
        isbn10:      "0674995619",
        notes:       "Greek text with facing English translation in 2 volumes.",
        goodreads:   "https://www.goodreads.com/book/show/101505",
        premium:     null,
        premiumUrl:  null,
      },
    ],
  },

  // ── HOMERIC HYMNS ─────────────────────────────────
  {
    workTitle:    "Homeric Hymns",
    author:       "Anonymous",
    date:         "c. 7th–5th century BC",
    editions: [
      {
        type:        "English Translation",
        translator:  "Apostolos N. Athanassakis",
        publisher:   "Johns Hopkins University Press",
        series:      null,
        year:        2020,
        pages:       144,
        isbn:        "9781421438603",
        isbn10:      "1421438607",
        notes:       "Third edition — the best-selling essential translation. Concise, accurate, scholarly.",
        goodreads:   "https://www.goodreads.com/book/show/48694197",
        premium:     null,
        premiumUrl:  null,
      },
      {
        type:        "Greek-English (Loeb)",
        translator:  "Martin L. West",
        publisher:   "Harvard University Press",
        series:      "Loeb Classical Library No. 496",
        year:        2003,
        pages:       316,
        isbn:        "9780674996052",
        isbn10:      "0674996054",
        notes:       "Includes Homeric Apocrypha and Lives of Homer. Greek with facing English.",
        goodreads:   "https://www.goodreads.com/book/show/816830",
        premium:     null,
        premiumUrl:  null,
      },
    ],
  },
];

// ─────────────────────────────────────────────────────
//  SHEET 2: TRAGEDY
// ─────────────────────────────────────────────────────

// ── AESCHYLUS ─────────────────────────────────────────
const aeschylus = [
  {
    workTitle: "Oresteia (Agamemnon · Libation Bearers · Eumenides)",
    date:      "c. 458 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Robert Fagles",
        publisher:  "Penguin Classics",
        series:     "Penguin Classics",
        year:       1977,
        pages:      336,
        isbn:       "9780140443332",
        isbn10:     "0140443339",
        notes:      "Landmark verse translation. Nominated for the National Book Award. Introduction by W.B. Stanford.",
        goodreads:  "https://www.goodreads.com/book/show/400566",
        premium:    "The Folio Society",
        premiumUrl: "https://www.foliosociety.com/row/the-oresteia.html",
      },
      {
        type:       "Greek-English (Loeb) — Vol II of 3-vol set",
        translator: "Alan H. Sommerstein",
        publisher:  "Harvard University Press",
        series:     "Loeb Classical Library No. 146",
        year:       2008,
        pages:      560,
        isbn:       "9780674996281",
        isbn10:     "0674996283",
        notes:      "New Loeb with facing Greek text. Vol. II of Sommerstein's complete Aeschylus set.",
        goodreads:  "https://www.goodreads.com/book/show/6481614",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Prometheus Bound",
    date:      "c. 460 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "James Scully & C.J. Herington",
        publisher:  "Oxford University Press",
        series:     null,
        year:       1975,
        pages:      176,
        isbn:       "9780195061659",
        isbn10:     "0195061659",
        notes:      "Highly praised scholarly translation with introduction by Herington. The best standalone edition.",
        goodreads:  "https://www.goodreads.com/book/show/1186977",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Seven Against Thebes",
    date:      "c. 467 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Anthony Hecht & Helen Bacon",
        publisher:  "Oxford University Press",
        series:     null,
        year:       1973,
        pages:      112,
        isbn:       "9780195017137",
        isbn10:     "0195017137",
        notes:      "Poetic translation by Pulitzer-winning poet Hecht. Vivid and dramatically effective.",
        goodreads:  "https://www.goodreads.com/book/show/274308",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "The Persians",
    date:      "c. 472 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Janet Lembke & C.J. Herington",
        publisher:  "Oxford University Press",
        series:     null,
        year:       1991,
        pages:      160,
        isbn:       "9780195070088",
        isbn10:     "0195070089",
        notes:      "Only surviving Greek tragedy set on a contemporary event (Battle of Salamis). Authoritative translation.",
        goodreads:  "https://www.goodreads.com/book/show/272698",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "The Suppliants",
    date:      "c. 463 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Peter Burian",
        publisher:  "Princeton University Press",
        series:     null,
        year:       1991,
        pages:      152,
        isbn:       "9780691014951",
        isbn10:     "0691014957",
        notes:      "Best scholarly translation of Aeschylus' earliest surviving play. With full commentary.",
        goodreads:  "https://www.goodreads.com/book/show/2154302",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Complete Plays of Aeschylus",
    date:      "c. 490–458 BC",
    editions: [
      {
        type:       "Greek-English (Loeb) — 3 vols",
        translator: "Alan H. Sommerstein",
        publisher:  "Harvard University Press",
        series:     "Loeb Classical Library No. 145, 146, 505",
        year:       2009,
        vol1Pages:  544,
        vol2Pages:  560,
        vol3Pages:  400,
        isbn1:      "9780674996274",
        isbn2:      "9780674996281",
        isbn3:      "9780674996298",
        isbn10:     "0674996275",
        notes:      "Vol I: Persians/Seven/Suppliants/Prometheus. Vol II: Oresteia. Vol III: Fragments. Complete Aeschylus.",
        goodreads:  "https://www.goodreads.com/series/58841",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
];

// ── SOPHOCLES ─────────────────────────────────────────
const sophocles = [
  {
    workTitle: "Three Theban Plays: Antigone · Oedipus the King · Oedipus at Colonus",
    date:      "c. 441–401 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Robert Fagles",
        publisher:  "Penguin Classics",
        series:     "Penguin Classics",
        year:       1984,
        pages:      432,
        isbn:       "9780140444254",
        isbn10:     "0140444254",
        notes:      "The most-read Sophocles in English. Introduction by Bernard Knox. Read these three first.",
        goodreads:  "https://www.goodreads.com/book/show/153747",
        premium:    "The Folio Society",
        premiumUrl: "https://www.foliosociety.com/row/the-theban-plays.html",
      },
    ],
  },
  {
    workTitle: "Electra",
    date:      "c. 410 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "H.D.F. Kitto, intro. Edith Hall",
        publisher:  "Oxford University Press",
        series:     "Oxford World's Classics",
        year:       2008,
        pages:      224,
        isbn:       "9780199537174",
        isbn10:     "0199537178",
        notes:      "Tighter and more brutal than Euripides' Electra. Kitto's translation is widely praised for precision.",
        goodreads:  "https://www.goodreads.com/book/show/271549",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Ajax",
    date:      "c. 440s BC",
    editions: [
      {
        type:       "English Translation",
        translator: "John Moore",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Sophocles I",
        year:       1957,
        pages:      160,
        isbn:       "9780226308838",
        isbn10:     "0226308839",
        notes:      "In Grene-Lattimore Sophocles I (Chicago). The hero who cannot adapt — Sophocles' earliest surviving play.",
        goodreads:  "https://www.goodreads.com/book/show/271567",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Philoctetes",
    date:      "c. 409 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "David Grene",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Sophocles II",
        year:       1957,
        pages:      160,
        isbn:       "9780226308845",
        isbn10:     "0226308847",
        notes:      "In Grene-Lattimore Sophocles II. Isolation, betrayal, duty. One of Sophocles' greatest late plays.",
        goodreads:  "https://www.goodreads.com/book/show/271563",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Women of Trachis (Trachiniae)",
    date:      "c. 440s BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Michael Jameson",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Sophocles II",
        year:       1957,
        pages:      176,
        isbn:       "9780226308845",
        isbn10:     "0226308847",
        notes:      "In Grene-Lattimore Sophocles II. Heracles' death by Nessus' poisoned cloak. Often overlooked masterpiece.",
        goodreads:  "https://www.goodreads.com/book/show/271561",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Complete Plays of Sophocles",
    date:      "c. 497–406 BC",
    editions: [
      {
        type:       "Greek-English (Loeb) — 2 vols",
        translator: "Hugh Lloyd-Jones",
        publisher:  "Harvard University Press",
        series:     "Loeb Classical Library No. 20 & 21",
        year:       1994,
        vol1Pages:  496,
        vol2Pages:  600,
        isbn1:      "9780674995574",
        isbn2:      "9780674995581",
        isbn10:     "0674995573",
        notes:      "Vol I: Ajax/Electra/Oedipus Rex. Vol II: Antigone/Trachiniae/Philoctetes/Oedipus at Colonus.",
        goodreads:  "https://www.goodreads.com/book/show/2454527",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
];

// ── EURIPIDES ─────────────────────────────────────────
const euripides = [
  {
    workTitle: "Medea",
    date:      "c. 431 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Rex Warner",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides I",
        year:       1955,
        pages:      224,
        isbn:       "9780226308807",
        isbn10:     "0226308804",
        notes:      "Warner's Medea remains the definitive scholarly verse translation. Fierce, exact, unforgettable.",
        goodreads:  "https://www.goodreads.com/book/show/49049",
        premium:    "The Folio Society",
        premiumUrl: "https://www.foliosociety.com/row/medea.html",
      },
    ],
  },
  {
    workTitle: "The Bacchae",
    date:      "c. 405 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "William Arrowsmith",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides V",
        year:       1959,
        pages:      192,
        isbn:       "9780226308982",
        isbn10:     "0226308987",
        notes:      "Arrowsmith's Bacchae is widely considered the definitive English version. Dionysus vs. rationalism.",
        goodreads:  "https://www.goodreads.com/book/show/386142",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Hippolytus",
    date:      "c. 428 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "David Grene",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides I",
        year:       1955,
        pages:      224,
        isbn:       "9780226308807",
        isbn10:     "0226308804",
        notes:      "In Grene-Lattimore Euripides I. Aphrodite's wrath and forbidden desire. Won first prize at Athens.",
        goodreads:  "https://www.goodreads.com/book/show/271571",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "The Trojan Women",
    date:      "c. 415 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Richmond Lattimore",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides III",
        year:       1958,
        pages:      256,
        isbn:       "9780226308951",
        isbn10:     "0226308952",
        notes:      "The most devastating anti-war text in world literature. Lattimore's version is lyrical and devastating.",
        goodreads:  "https://www.goodreads.com/book/show/271576",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Alcestis",
    date:      "c. 438 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Richmond Lattimore",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides I",
        year:       1955,
        pages:      224,
        isbn:       "9780226308807",
        isbn10:     "0226308804",
        notes:      "A wife dies in her husband's place; Heracles wrestles Death. Part tragedy, part dark comedy.",
        goodreads:  "https://www.goodreads.com/book/show/271569",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Iphigenia in Aulis",
    date:      "c. 405 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Charles R. Walker",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides V",
        year:       1958,
        pages:      192,
        isbn:       "9780226308982",
        isbn10:     "0226308987",
        notes:      "A daughter sacrificed so the fleet sails to Troy. Gut-wrenching moral horror. Produced posthumously.",
        goodreads:  "https://www.goodreads.com/book/show/271574",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Iphigenia in Tauris",
    date:      "c. 414–412 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Witter Bynner",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides III",
        year:       1958,
        pages:      256,
        isbn:       "9780226308951",
        isbn10:     "0226308952",
        notes:      "Sister rescues brother in a foreign land. More hopeful than most Euripides. A proto-romance.",
        goodreads:  "https://www.goodreads.com/book/show/271572",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Electra",
    date:      "c. 420 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Emily Townsend Vermeule",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides IV",
        year:       1959,
        pages:      256,
        isbn:       "9780226308968",
        isbn10:     "0226308960",
        notes:      "Darker and more psychologically probing than Sophocles' Electra. Read both — the contrast is revealing.",
        goodreads:  "https://www.goodreads.com/book/show/271578",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Ion",
    date:      "c. 414–412 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "Ronald Frederick Willetts",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides IV",
        year:       1958,
        pages:      256,
        isbn:       "9780226308968",
        isbn10:     "0226308960",
        notes:      "Euripides' most structurally experimental play. Gods, identity, and abandonment. Surprisingly funny.",
        goodreads:  "https://www.goodreads.com/book/show/271573",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Heracles",
    date:      "c. 416 BC",
    editions: [
      {
        type:       "English Translation",
        translator: "William Arrowsmith",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies — Euripides III",
        year:       1956,
        pages:      256,
        isbn:       "9780226308951",
        isbn10:     "0226308952",
        notes:      "The great hero at his lowest. Madness, infanticide, divine injustice. A criminally underrated masterpiece.",
        goodreads:  "https://www.goodreads.com/book/show/271579",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
  {
    workTitle: "Complete Plays of Euripides",
    date:      "c. 480–406 BC",
    editions: [
      {
        type:       "English Translation (Chicago Complete)",
        translator: "David Grene & Richmond Lattimore (eds.)",
        publisher:  "University of Chicago Press",
        series:     "Complete Greek Tragedies",
        year:       1992,
        pages:      null,
        isbn:       "9780226307633",
        isbn10:     "0226307638",
        notes:      "The definitive English collection of all surviving Euripides plays. An essential shelf item.",
        goodreads:  "https://www.goodreads.com/book/show/271568",
        premium:    null,
        premiumUrl: null,
      },
      {
        type:       "Greek-English (Loeb) — 6 vols",
        translator: "David Kovacs",
        publisher:  "Harvard University Press",
        series:     "Loeb Classical Library No. 12, 484, 9, 10, 11, 495",
        year:       2002,
        vol1Pages:  432,
        vol2Pages:  500,
        vol3Pages:  496,
        vol4Pages:  560,
        vol5Pages:  512,
        vol6Pages:  480,
        isbn1:      "9780674995604",
        isbn2:      "9780674995338",
        isbn3:      "9780674995728",
        isbn4:      "9780674995741",
        isbn5:      "9780674995888",
        isbn6:      "9780674996014",
        isbn10:     "0674995603",
        notes:      "Complete Euripides with facing Greek text. 6 volumes. The ultimate reference for Greek drama scholars.",
        goodreads:  "https://www.goodreads.com/series/58839",
        premium:    null,
        premiumUrl: null,
      },
    ],
  },
];
